### ISSUE TITLE
Mesh refinement of the current grid

### ISSUE THREAD

**Issue by HFH104864** [GeoMop/bgem#24]
I obtained a grid file by meshed the STL model.However, I found that the grid size obtained was not appropriate, and I hope to refine the grid. May I ask if there is any solution in GMSH to solve this problem.

thank you !
best wish  !

**Comment by Paulie14** [comment]
Hi @HFH104864!
I am not sure, whether you used our BGEM lib to create the mesh..

If you already have a mesh file, then your options with GMSH are limited, I suppose.
You can apply `Refine by splitting` to make your mesh globally finer.

If you start with `geo` file, then you can set the mesh step as an argument of `Point` and control the mesh step locally.

Using BGEM, you can assign region names and mesh step size to the geometric entities:
```
object.set_region("my_region")
object.mesh_step(0.2)
```

**Comment by HFH104864** [comment]
Actually, I remesh an STL model according to the t13 tutorial to get a grid file in VTK format

**Comment by HFH104864** [comment]
And I star with an STL file

**Comment by Paulie14** [comment]
Aah, ok. I am sorry, I can't help you as I don't have experience with combination STL+GMSH+VTK.
We are working mainly with GMSH and MSH meshes, and VTK format for output of our simulator Flow123d.

**Comment by HFH104864** [comment]
Thank you for your response . By the way , now I am trying to change the mesh size when doing stl remesh ,  and I used gmsh API field::add and field::setstring ,but it seem nothing changed . My code is as follow：

 using namespace gmsh;
        double lc = 1;
        initialize();
        gmsh::model::add("t13");
 double angle = 40;//定义尖边
        bool forceParametrizablePatches = false;
        bool includeBoundary = true;
        double curveAngle = 180;
        gmsh::model::mesh::classifySurfaces(angle * M_PI / 180., includeBoundary,
            forceParametrizablePatches,
            curveAngle * M_PI / 180.);
        /*gmsh::vectorpair dimTags(3);*/
      /*  gmsh::model::mesh::createGeometry();*/
        std::vector<std::pair<int, int> > s;
        gmsh::model::getEntities(s, 2);
        std::vector<int> sl;
        for (auto surf : s) sl.push_back(surf.second);
        int l = gmsh::model::geo::addSurfaceLoop(sl);
        gmsh::model::geo::addVolume({ l });
        gmsh::model::addPhysicalGroup(3, { 1 }, 1);
        gmsh::model::geo::synchronize();
    
        bool funny = true; // false;
        int f = gmsh::model::mesh::field::add("MathEval");
        if (funny)
            gmsh::model::mesh::field::setString(f, "F", "2*Sin((x+y)/5) + 3");
        else
            gmsh::model::mesh::field::setString(f, "F", "4");
      
        gmsh::model::mesh::field::setAsBackgroundMesh(f);
        /* gmsh::option::setNumber("General.ClipPositionY", 150);*/
        gmsh::model::mesh::generate(3);
        gmsh::write("temp.vtk");
        gmsh::finalize();

Is there any way to control the mesh size obtained by STL remeshing

**Comment by jbrezmorf** [comment]
The issue is related to the GMS python API not to the BGEM wrapper.
